language: ruby
rvm:
  - 2.4.2

sudo: required
before_install:
  - sudo update-ca-certificates

before_script:
  - chmod +x ./script/cibuild

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

env:
  global:
    # speeds up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

# route your build to the container-based infrastructure for a faster build
sudo: false