baseurl: ''
collections:
  coll_chapter: {output: true, permalink: '/chapter/:name'}
  coll_citation: {output: true, permalink: '/citation/:name'}
  coll_country: {output: true, permalink: '/country/:name'}
  coll_country_information: {output: true, permalink: '/country_information/:name'}
  coll_country_key_facts: {output: true, permalink: '/country_key_facts/:name'}
  coll_featured_site: {output: true, permalink: '/featured_site/:name'}
  coll_introduction: {output: true, permalink: '/introduction/:name'}
  coll_thematic: {output: true, permalink: '/thematic/:name'}
contentful:
  spaces:
  - ara: {access_token: ENV_CONTENTFUL_ACCESS_TOKEN, all_entries: false, destination: '',
      space: ENV_CONTENTFUL_SPACE_ID}
description: African Rock Art Follow our digital journey across Africa. Discover 30,000
  years of rock art.
email: info@britishmuseum.org
github_username: kingsdigitallab
google_analytics: UA-1005261-36
include: [_pages]
markdown: kramdown
plugins: [jekyll-feed]
theme: minima
title: African Rock Art
twitter_username: britishmuseum
url: http://africanrockart.britishmuseum.org
